---
- block:
  - name: Create persistence file dir
    file:
      path: "{{ pushgateway_persistence_dir }}"
      state: directory
      owner: "root"
      group: "root"
      mode: 0755

  - name: Create persistence file
    file:
      path: "{{ pushgateway_persistence_dir }}/persistence"
      state: touch
      owner: "{{ pushgateway_system_user }}"
      group: "{{ pushgateway_system_group }}"
      mode: 0640
    register: touch_log
    changed_when: touch_log.diff.before.state != "file"
  when: pushgateway_persistence