---
- import_tasks: preflight.yml
  tags:
    - pushgateway

- import_tasks: install.yml
  become: true
  tags:
    - install

- import_tasks: configure.yml
  become: true
  tags:
    - configure

- name: Ensure pushgateway is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: pushgateway
    enabled: true
  tags:
    - run
