---

- name: GRAFANA | Configuring service
  systemd:
    name: grafana-server
    state: "{{ grafana_service_state }}"
    enabled: "{{ grafana_service_enabled }}"
    daemon_reload: yes

- name: GRAFANA | Wait for service listening
  wait_for:
    host: "{{ grafana_host }}"
    port: "{{ grafana_port }}"
    state: "{{ grafana_service_state }}"
    timeout: 30
