---
- name: Setup Prometheus on Gcloud
  hosts:
    - prometheus
  become: true
  gather_facts: true
  roles:
    - { role: monitorings/node-exporter, tags: node-exporter }
    - { role: monitorings/prometheus, tags: prometheus }
    - { role: monitorings/grafana, tags: grafana }
    - { role: nginx, tags: nginx }
    - { role: monitorings/blackbox-exporter, tags: ['blackbox-exporter'] }