---
blackbox_exporter_version: "0.16.0"

blackbox_exporter_root_dir: "/opt/blackbox_exporter"

blackbox_exporter_web_listen_address: "0.0.0.0:9115"

blackbox_exporter_cli_flags: {}

blackbox_exporter_configuration_modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      no_follow_redirects: false
      preferred_ip_protocol: "ip4"
  tcp_connect:
    prober: tcp
    timeout: 5s
  ssh_banner:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^SSH-2.0-"